### ISSUE TITLE
NoMethodError: undefined method `f' for Memo:Module

### ISSUE THREAD

**Issue by 404pnf** [rhysd/memo#1]
## ruby versioin

ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]
## it doesn't work?
1. install the gem,  gem install memo
2. in irb
   
   > > require 'memo'
   > >   => true
   > > Memo.f do |n|
   > >   ?> sleep 1
   > > end
   > >   NoMethodError: undefined method `f' for Memo:Module
   > >     from (irb):2
   > >     from /Users/someuser/.rvm/rubies/ruby-2.1.1/bin/irb:11:in`<main>'
## But it works
1. clone the repo and go to the lib dir. 
2.  in irb
   
   > > load 'memo.rb'
   > >   => true
   > > Memo.f do |n|
   > >   ?> sleep n
   > > end
   > >   => :f 
   > > Memo.f 3
   > >   => 3

**Comment by rhysd** [comment]
Current version doesn't seem to occur this problem.

``` sh
$ cd /path/to/memo
$ pry
$ > $LOAD_PATHS << './lib'
$ > Memo.foo do |n|
$ *   sleep n
$ * end
$ > Memo.foo 1
$ > # No error
```
